### ISSUE TITLE
3.20.18

### ISSUE THREAD

**Issue by jraeglasgow** [jraeglasgow/Neda-1-1#1]

**Comment by nedaraeva** [comment]
### Game plan for end of March and how to hit full quota in April:

✔️ [Neda's working playbook with Messaging and Personas](docs.google.com/spreadsheets/d/17X3CFwSpivMsoXmRcyWJZBb-tSdSG_uSgZWPzqHomy0/edit#gid=0)

- [ ] 30 calls a day
- [ ] 20 first touch emails a day
- [ ] drive Constellation LA attendance ➡️ SPIFS & LEADS (cadence already created)
- [ ] work with tenured folks on persona specific messaging and questions 
- [ ] improve communication with my reps ➡️ reoccurring strategy meetings

**Comment by jraeglasgow** [comment]
Good job adding the 1 hour of product study @nedaraeva 👍 Make sure you schedule it like we talked about so it doesn't fall off the radar.
