### ISSUE TITLE
4.9.18

### ISSUE THREAD

**Issue by jraeglasgow** [jraeglasgow/Neda-1-1#2]
## **Last Week Activities** 
- Calls:
- Total Emails:
- New Contacts in Cadences Launched: 
- Meetings Set:
- Most Effective Personas:
- Stack Ranking/Focus from ESR: 

## **Goals**
- This Week Activity
    - Calls:
    - Total Emails:
    - New Contacts Launched in Cadences:
- Personal: What are your daily habits that will make you better?   
- BHAG: Work/Personal 

## **Events**
Upcoming Opportunity 
- Constellation LA: April 10-11
- MicrosoftBuild: May 7-9th
- Constellation Portland: May 22
- West QBR: May 15-17 

## Feedback and Questions 
- good job asking Jen to copy you on the email communications to support tandem attack approach 
- Panasonic and Warner Bros - do you have a wholistic view rather than just individual  
-set goals around some accounts and pick AEG (green accounts?) on doc and follow up on progress there so she knows you are working on those 
- have Agenda with Jenn and Zo when you get on calls that includes but is not limited to: 
EX:
- [ ] recap last meetings/flip what is needed
- [ ] ESR's focus for the week (strategize how you can tandem attack here) 
- [ ] connect and directly rep to your weekly goals ex: 20 highly custom messages to (x) personas and 20 net new contacts in cadences per week

**Comment by nedaraeva** [comment]
**Zo:** breaking companies by vertical & will work campaigns per industry (ex: healthcare, retail, tech)
- [ ] Top targets: Polycom aka Plantronics, Sanmina SCI, Marvell, PG&E

**Jenn:** follow up on meetings held ➡️ drive convo forward 
- [ ] Top targets: WB, Panasonic Aero, AEG

**Comment by jraeglasgow** [comment]
Goals: Create campaign for vertical specific industries - Wednesday , Launch Contacts in those on Friday - 20 new contacts for Zo
-Next Week Goal would to be launch 20/daily but mix of Jenn and Zo
