### ISSUE TITLE
May Planning - 4.24.18 1/1

### ISSUE THREAD

**Issue by jraeglasgow** [jraeglasgow/Neda-1-1#3]
Hi @nedaraeva ,

For our last one-on-one this month, I want to focus on a plan for May. Below is an outline of our monthly approach to success. I included specific goals you and I have discussed, connecting them to action items, as well as  feedback on last month to take into May. Please let me know if you have any questions and I look forward to reviewing this together tomorrow. Note, the outline is all that needs to be done by the meeting, I wanted to give you a full week to finish your assets so you can focus on the end of the month as well! (Also note, the Master Issue Template should be ready by tomorrow, just wrapping up a few things.)

-Jess
___________________________________________________________________________________________________________
**May Plan** 

**What**: Need 7 Meetings to Hit - 11 to Hit 150%
**Who**: Top 5 Accounts/ ESR that will get you to 150%
**When**: 
- Week 1 Activities 
- Week 2 Activities 
- Week 3 Activities
- Week 4 Activities 

**How**:
- Workflow: tools used, execution details: 
- cadences used 

**Action Items**: 
- [x] **Who**: Pick Top 5 Accounts/Rep and Finish Master Issue and Tier Sheet for Each by EOD Monday, April 30th 
- [x] **When**: Map which activities to weeks to create plan to reach goal of 11 meetings (BHAG is to do so well that you can further promote work/life balance) *be sure to include qualitative evaluation as well 
- [x] **How**: outline ( high level example of how you are going to execute your plan for May) 

**April Feedback** 
- good job of implementing feedback on meetings and gaining more insight into wholistic view of accounts 
- added week of Product Study but fell off, how are you making sure you become the expect on your accounts 
- approach to accounts should include more ownership of the result not just the action - quantity v. quality 
- good job proactively asking for feedback on content and messaging 

**Assets**: 

- [SalesDev Account Tier/Mapping Template
](https://docs.google.com/spreadsheets/d/1W2FbnQrdPdLaCUsVQPJQq7YcUmN4IgAlRPA2xkqnlI4/edit#gid=1762991169)
- Master Issue Template 
## Company X

**SFDC** (link to Salesforce search for 'Company X')
**LinkedIn** 
**DiscoverOrg**
**Master spreadsheet**
**HQ:**  

#### VCS info
- **Current VCS:** 
- **Past GitHub trials:** 
- **Noticeable GitHub.com presence?** 

#### Context
- **Any similar customers?** (look for trends, key words, what's driving change?)
- **Any known tech initiatives?** (could be based on past conversations and/or on current info in the news)
- **Any known BUs? Which ones are we approaching?**
- **Key stakeholders:** (could be based on past conversations and/or on current info in the news)

#### 1st campaign: [who's being targetted]  
- **Why them?**
- **Target contacts:** (individuals, personas, or a specific BU)
  - ...

### Links to related Issues, Halp threads, SFDC notes
- ...

**Comment by nedaraeva** [comment]
### Top 5 Accounts:
- Zo: Western Union, PG&E, Polycom and Plantronics, Live Nation, FICO
- Jenn: Amgen, AEG, Broadcom, Panasonic Avionics, T-Systems

### Activities:

- Campaigns per industry
- Ask for contacts for current instal accounts 
- Thursdays send roadmap messaging per Michelle's workflow + Sunday bump
- 20 contacts a day in SFDC
- 30 calls a day
- 20 personalized emails

**Comment by jraeglasgow** [comment]
@nedaraeva food for thought - take a look at the above and see how much the top targets have changed and why ( nothing to submit just a good learning experience)
